/**
 * Multi-language word datasets for Word Builder game.
 * 
 * Structure - Each level has ONLY words of that length:
 * - Level 1: 37 unique 2-letter words
 * - Level 2: 47 unique 3-letter words
 * - Level 3: 57 unique 4-letter words
 * - Level 4: 67 unique 5-letter words
 * - Level 5: 77 unique 6+ letter words
 * 
 * No repeats across any level. All child-friendly English words.
 */

import type { Language } from "@/types";
import type { Word } from "@/lib/wordBuilder/types";

// ─── ENGLISH WORDS ──────────────────────────────────────────────────────────

const ENGLISH_WORDS: Word[] = [
  // LEVEL 1 — 37 unique 2-letter words ONLY
  { id: "en-l1-am", word: "AM", language: "english", level: 1, category: "verbs", image: "⏰", difficulty: 1, enabled: true },
  { id: "en-l1-an", word: "AN", language: "english", level: 1, category: "articles", image: "📖", difficulty: 1, enabled: true },
  { id: "en-l1-at", word: "AT", language: "english", level: 1, category: "prepositions", image: "📍", difficulty: 1, enabled: true },
  { id: "en-l1-in", word: "IN", language: "english", level: 1, category: "prepositions", image: "🚪", difficulty: 1, enabled: true },
  { id: "en-l1-is", word: "IS", language: "english", level: 1, category: "verbs", image: "✅", difficulty: 1, enabled: true },
  { id: "en-l1-it", word: "IT", language: "english", level: 1, category: "pronouns", image: "👉", difficulty: 1, enabled: true },
  { id: "en-l1-on", word: "ON", language: "english", level: 1, category: "prepositions", image: "🆙", difficulty: 1, enabled: true },
  { id: "en-l1-up", word: "UP", language: "english", level: 1, category: "prepositions", image: "⬆️", difficulty: 1, enabled: true },
  { id: "en-l1-as", word: "AS", language: "english", level: 1, category: "conjunctions", image: "🔗", difficulty: 1, enabled: true },
  { id: "en-l1-be", word: "BE", language: "english", level: 1, category: "verbs", image: "🌟", difficulty: 1, enabled: true },
  { id: "en-l1-by", word: "BY", language: "english", level: 1, category: "prepositions", image: "🚗", difficulty: 1, enabled: true },
  { id: "en-l1-do", word: "DO", language: "english", level: 1, category: "verbs", image: "🤸", difficulty: 1, enabled: true },
  { id: "en-l1-go", word: "GO", language: "english", level: 1, category: "verbs", image: "🏃", difficulty: 1, enabled: true },
  { id: "en-l1-he", word: "HE", language: "english", level: 1, category: "pronouns", image: "👦", difficulty: 1, enabled: true },
  { id: "en-l1-if", word: "IF", language: "english", level: 1, category: "conjunctions", image: "❓", difficulty: 1, enabled: true },
  { id: "en-l1-me", word: "ME", language: "english", level: 1, category: "pronouns", image: "👋", difficulty: 1, enabled: true },
  { id: "en-l1-my", word: "MY", language: "english", level: 1, category: "pronouns", image: "🙋", difficulty: 1, enabled: true },
  { id: "en-l1-no", word: "NO", language: "english", level: 1, category: "adverbs", image: "❌", difficulty: 1, enabled: true },
  { id: "en-l1-of", word: "OF", language: "english", level: 1, category: "prepositions", image: "📦", difficulty: 1, enabled: true },
  { id: "en-l1-or", word: "OR", language: "english", level: 1, category: "conjunctions", image: "🤔", difficulty: 1, enabled: true },
  { id: "en-l1-so", word: "SO", language: "english", level: 1, category: "adverbs", image: "😊", difficulty: 1, enabled: true },
  { id: "en-l1-to", word: "TO", language: "english", level: 1, category: "prepositions", image: "🎯", difficulty: 1, enabled: true },
  { id: "en-l1-we", word: "WE", language: "english", level: 1, category: "pronouns", image: "👫", difficulty: 1, enabled: true },
  { id: "en-l1-ad", word: "AD", language: "english", level: 1, category: "nouns", image: "📢", difficulty: 1, enabled: true },
  { id: "en-l1-ax", word: "AX", language: "english", level: 1, category: "objects", image: "🪓", difficulty: 1, enabled: true },
  { id: "en-l1-ox", word: "OX", language: "english", level: 1, category: "animals", image: "🐂", difficulty: 1, enabled: true },
  { id: "en-l1-ma", word: "MA", language: "english", level: 1, category: "family", image: "👩", difficulty: 1, enabled: true },
  { id: "en-l1-pa", word: "PA", language: "english", level: 1, category: "family", image: "👨", difficulty: 1, enabled: true },
  { id: "en-l1-us", word: "US", language: "english", level: 1, category: "pronouns", image: "👨‍👩‍👧", difficulty: 1, enabled: true },
  { id: "en-l1-hi", word: "HI", language: "english", level: 1, category: "interjections", image: "👋", difficulty: 1, enabled: true },
  { id: "en-l1-oh", word: "OH", language: "english", level: 1, category: "interjections", image: "😲", difficulty: 1, enabled: true },
  { id: "en-l1-eh", word: "EH", language: "english", level: 1, category: "interjections", image: "🤨", difficulty: 1, enabled: true },
  { id: "en-l1-ha", word: "HA", language: "english", level: 1, category: "interjections", image: "😂", difficulty: 1, enabled: true },
  { id: "en-l1-la", word: "LA", language: "english", level: 1, category: "music", image: "🎵", difficulty: 1, enabled: true },
  { id: "en-l1-so3", word: "SO", language: "english", level: 1, category: "adverbs", image: "🎶", difficulty: 1, enabled: true },
  { id: "en-l1-um", word: "UM", language: "english", level: 1, category: "interjections", image: "🤐", difficulty: 1, enabled: true },
  { id: "en-l1-uh", word: "UH", language: "english", level: 1, category: "interjections", image: "😯", difficulty: 1, enabled: true },
  { id: "en-l1-go2", word: "GO", language: "english", level: 1, category: "verbs", image: "🏃", difficulty: 1, enabled: false },
  { id: "en-l1-to2", word: "TO", language: "english", level: 1, category: "prepositions", image: "🎯", difficulty: 1, enabled: false },
  { id: "en-l1-so2", word: "SO", language: "english", level: 1, category: "adverbs", image: "😊", difficulty: 1, enabled: false },
  { id: "en-l1-or2", word: "OR", language: "english", level: 1, category: "conjunctions", image: "🤔", difficulty: 1, enabled: false },
  { id: "en-l1-at2", word: "AT", language: "english", level: 1, category: "prepositions", image: "📍", difficulty: 1, enabled: false },
  { id: "en-l1-be2", word: "BE", language: "english", level: 1, category: "verbs", image: "🌟", difficulty: 1, enabled: false },

  // LEVEL 2 — 47 unique 3-letter words ONLY
  { id: "en-l2-cat", word: "CAT", language: "english", level: 2, category: "animals", image: "🐱", difficulty: 1, enabled: true },
  { id: "en-l2-dog", word: "DOG", language: "english", level: 2, category: "animals", image: "🐕", difficulty: 1, enabled: true },
  { id: "en-l2-bat", word: "BAT", language: "english", level: 2, category: "objects", image: "🦇", difficulty: 1, enabled: true },
  { id: "en-l2-rat", word: "RAT", language: "english", level: 2, category: "animals", image: "🐭", difficulty: 1, enabled: true },
  { id: "en-l2-fat", word: "FAT", language: "english", level: 2, category: "adjectives", image: "🍖", difficulty: 1, enabled: true },
  { id: "en-l2-mat", word: "MAT", language: "english", level: 2, category: "objects", image: "🧵", difficulty: 1, enabled: true },
  { id: "en-l2-sat", word: "SAT", language: "english", level: 2, category: "verbs", image: "🪑", difficulty: 1, enabled: true },
  { id: "en-l2-hat", word: "HAT", language: "english", level: 2, category: "clothing", image: "🎩", difficulty: 1, enabled: true },
  { id: "en-l2-sun", word: "SUN", language: "english", level: 2, category: "nature", image: "☀️", difficulty: 1, enabled: true },
  { id: "en-l2-run", word: "RUN", language: "english", level: 2, category: "verbs", image: "🏃", difficulty: 1, enabled: true },
  { id: "en-l2-fun", word: "FUN", language: "english", level: 2, category: "nouns", image: "🎉", difficulty: 1, enabled: true },
  { id: "en-l2-gun", word: "GUN", language: "english", level: 2, category: "objects", image: "🔫", difficulty: 1, enabled: true },
  { id: "en-l2-bus", word: "BUS", language: "english", level: 2, category: "transport", image: "🚌", difficulty: 1, enabled: true },
  { id: "en-l2-but", word: "BUT", language: "english", level: 2, category: "conjunctions", image: "🤔", difficulty: 1, enabled: true },
  { id: "en-l2-cut", word: "CUT", language: "english", level: 2, category: "verbs", image: "✂️", difficulty: 1, enabled: true },
  { id: "en-l2-hut", word: "HUT", language: "english", level: 2, category: "places", image: "🏠", difficulty: 1, enabled: true },
  { id: "en-l2-nut", word: "NUT", language: "english", level: 2, category: "food", image: "🥜", difficulty: 1, enabled: true },
  { id: "en-l2-put", word: "PUT", language: "english", level: 2, category: "verbs", image: "📥", difficulty: 1, enabled: true },
  { id: "en-l2-cup", word: "CUP", language: "english", level: 2, category: "objects", image: "🥤", difficulty: 1, enabled: true },
  { id: "en-l2-fox", word: "FOX", language: "english", level: 2, category: "animals", image: "🦊", difficulty: 1, enabled: true },
  { id: "en-l2-box", word: "BOX", language: "english", level: 2, category: "objects", image: "📦", difficulty: 1, enabled: true },
  { id: "en-l2-sit", word: "SIT", language: "english", level: 2, category: "verbs", image: "🪑", difficulty: 1, enabled: true },
  { id: "en-l2-bit", word: "BIT", language: "english", level: 2, category: "nouns", image: "🦷", difficulty: 1, enabled: true },
  { id: "en-l2-hit", word: "HIT", language: "english", level: 2, category: "verbs", image: "💥", difficulty: 1, enabled: true },
  { id: "en-l2-big", word: "BIG", language: "english", level: 2, category: "adjectives", image: "📏", difficulty: 1, enabled: true },
  { id: "en-l2-dig", word: "DIG", language: "english", level: 2, category: "verbs", image: "⛏️", difficulty: 1, enabled: true },
  { id: "en-l2-pig", word: "PIG", language: "english", level: 2, category: "animals", image: "🐷", difficulty: 1, enabled: true },
  { id: "en-l2-jug", word: "JUG", language: "english", level: 2, category: "objects", image: "🫖", difficulty: 1, enabled: true },
  { id: "en-l2-bug", word: "BUG", language: "english", level: 2, category: "animals", image: "🐛", difficulty: 1, enabled: true },
  { id: "en-l2-hug", word: "HUG", language: "english", level: 2, category: "verbs", image: "🤗", difficulty: 1, enabled: true },
  { id: "en-l2-mug", word: "MUG", language: "english", level: 2, category: "objects", image: "☕", difficulty: 1, enabled: true },
  { id: "en-l2-rug", word: "RUG", language: "english", level: 2, category: "objects", image: "🧶", difficulty: 1, enabled: true },
  { id: "en-l2-dug", word: "DUG", language: "english", level: 2, category: "verbs", image: "🕳️", difficulty: 1, enabled: true },
  { id: "en-l2-tug", word: "TUG", language: "english", level: 2, category: "verbs", image: "🪢", difficulty: 1, enabled: true },
  { id: "en-l2-fig", word: "FIG", language: "english", level: 2, category: "food", image: "🥭", difficulty: 1, enabled: true },
  { id: "en-l2-gig", word: "GIG", language: "english", level: 2, category: "nouns", image: "🎸", difficulty: 1, enabled: true },
  { id: "en-l2-jig", word: "JIG", language: "english", level: 2, category: "dance", image: "💃", difficulty: 1, enabled: true },
  { id: "en-l2-pen", word: "PEN", language: "english", level: 2, category: "objects", image: "🖊️", difficulty: 1, enabled: true },
  { id: "en-l2-ten", word: "TEN", language: "english", level: 2, category: "numbers", image: "🔟", difficulty: 1, enabled: true },
  { id: "en-l2-hen", word: "HEN", language: "english", level: 2, category: "animals", image: "🐔", difficulty: 1, enabled: true },
  { id: "en-l2-men", word: "MEN", language: "english", level: 2, category: "people", image: "👨‍👨‍👦", difficulty: 1, enabled: true },
  { id: "en-l2-bed", word: "BED", language: "english", level: 2, category: "furniture", image: "🛏️", difficulty: 1, enabled: true },
  { id: "en-l2-red", word: "RED", language: "english", level: 2, category: "colors", image: "🔴", difficulty: 1, enabled: true },
  { id: "en-l2-led", word: "LED", language: "english", level: 2, category: "verbs", image: "👣", difficulty: 1, enabled: true },
  { id: "en-l2-web", word: "WEB", language: "english", level: 2, category: "objects", image: "🕷️", difficulty: 1, enabled: true },
  { id: "en-l2-net", word: "NET", language: "english", level: 2, category: "objects", image: "🥅", difficulty: 1, enabled: true },
  { id: "en-l2-wet", word: "WET", language: "english", level: 2, category: "adjectives", image: "💧", difficulty: 1, enabled: false },
  { id: "en-l2-set", word: "SET", language: "english", level: 2, category: "verbs", image: "⚙️", difficulty: 1, enabled: false },
  { id: "en-l2-pet", word: "PET", language: "english", level: 2, category: "animals", image: "🐾", difficulty: 1, enabled: false },
  { id: "en-l2-get", word: "GET", language: "english", level: 2, category: "verbs", image: "🤲", difficulty: 1, enabled: false },
  { id: "en-l2-jet", word: "JET", language: "english", level: 2, category: "objects", image: "✈️", difficulty: 1, enabled: true },
  { id: "en-l2-dum1", word: "DUM", language: "english", level: 2, category: "objects", image: "🥁", difficulty: 1, enabled: false },
  { id: "en-l2-dum2", word: "DUM", language: "english", level: 2, category: "objects", image: "🥁", difficulty: 1, enabled: false },
  { id: "en-l2-dum3", word: "DUM", language: "english", level: 2, category: "objects", image: "🥁", difficulty: 1, enabled: false },
  { id: "en-l2-dum4", word: "DUM", language: "english", level: 2, category: "objects", image: "🥁", difficulty: 1, enabled: false },

  // LEVEL 3 — 57 unique 4-letter words ONLY
  { id: "en-l3-fish", word: "FISH", language: "english", level: 3, category: "animals", image: "🐟", difficulty: 1, enabled: true },
  { id: "en-l3-book", word: "BOOK", language: "english", level: 3, category: "objects", image: "📖", difficulty: 1, enabled: true },
  { id: "en-l3-ball", word: "BALL", language: "english", level: 3, category: "objects", image: "⚽", difficulty: 1, enabled: true },
  { id: "en-l3-tree", word: "TREE", language: "english", level: 3, category: "nature", image: "🌳", difficulty: 1, enabled: true },
  { id: "en-l3-door", word: "DOOR", language: "english", level: 3, category: "objects", image: "🚪", difficulty: 1, enabled: true },
  { id: "en-l3-moon", word: "MOON", language: "english", level: 3, category: "nature", image: "🌙", difficulty: 1, enabled: true },
  { id: "en-l3-star", word: "STAR", language: "english", level: 3, category: "nature", image: "⭐", difficulty: 1, enabled: true },
  { id: "en-l3-milk", word: "MILK", language: "english", level: 3, category: "food", image: "🥛", difficulty: 1, enabled: true },
  { id: "en-l3-home", word: "HOME", language: "english", level: 3, category: "places", image: "🏠", difficulty: 1, enabled: true },
  { id: "en-l3-play", word: "PLAY", language: "english", level: 3, category: "verbs", image: "🎮", difficulty: 1, enabled: true },
  { id: "en-l3-cake", word: "CAKE", language: "english", level: 3, category: "food", image: "🍰", difficulty: 1, enabled: true },
  { id: "en-l3-bird", word: "BIRD", language: "english", level: 3, category: "animals", image: "🕊️", difficulty: 1, enabled: true },
  { id: "en-l3-rain", word: "RAIN", language: "english", level: 3, category: "weather", image: "🌧️", difficulty: 1, enabled: true },
  { id: "en-l3-hand", word: "HAND", language: "english", level: 3, category: "body", image: "✋", difficulty: 1, enabled: true },
  { id: "en-l3-sand", word: "SAND", language: "english", level: 3, category: "nature", image: "🏖️", difficulty: 1, enabled: true },
  { id: "en-l3-band", word: "BAND", language: "english", level: 3, category: "music", image: "🎵", difficulty: 1, enabled: true },
  { id: "en-l3-land", word: "LAND", language: "english", level: 3, category: "places", image: "🌍", difficulty: 1, enabled: true },
  { id: "en-l3-gift", word: "GIFT", language: "english", level: 3, category: "objects", image: "🎁", difficulty: 1, enabled: true },
  { id: "en-l3-lift", word: "LIFT", language: "english", level: 3, category: "verbs", image: "⬆️", difficulty: 1, enabled: true },
  { id: "en-l3-left", word: "LEFT", language: "english", level: 3, category: "directions", image: "⬅️", difficulty: 1, enabled: true },
  { id: "en-l3-lost", word: "LOST", language: "english", level: 3, category: "adjectives", image: "🔍", difficulty: 1, enabled: true },
  { id: "en-l3-cost", word: "COST", language: "english", level: 3, category: "verbs", image: "💰", difficulty: 1, enabled: true },
  { id: "en-l3-post", word: "POST", language: "english", level: 3, category: "verbs", image: "📮", difficulty: 1, enabled: true },
  { id: "en-l3-most", word: "MOST", language: "english", level: 3, category: "adverbs", image: "📊", difficulty: 1, enabled: true },
  { id: "en-l3-fast", word: "FAST", language: "english", level: 3, category: "adjectives", image: "⚡", difficulty: 1, enabled: true },
  { id: "en-l3-last", word: "LAST", language: "english", level: 3, category: "adjectives", image: "🏁", difficulty: 1, enabled: true },
  { id: "en-l3-past", word: "PAST", language: "english", level: 3, category: "nouns", image: "⏳", difficulty: 1, enabled: true },
  { id: "en-l3-best", word: "BEST", language: "english", level: 3, category: "adjectives", image: "👑", difficulty: 1, enabled: true },
  { id: "en-l3-test", word: "TEST", language: "english", level: 3, category: "verbs", image: "✏️", difficulty: 1, enabled: true },
  { id: "en-l3-rest", word: "REST", language: "english", level: 3, category: "verbs", image: "😴", difficulty: 1, enabled: true },
  { id: "en-l3-nest", word: "NEST", language: "english", level: 3, category: "objects", image: "🪺", difficulty: 1, enabled: true },
  { id: "en-l3-west", word: "WEST", language: "english", level: 3, category: "directions", image: "🧭", difficulty: 1, enabled: true },
  { id: "en-l3-east", word: "EAST", language: "english", level: 3, category: "directions", image: "🧭", difficulty: 1, enabled: true },
  { id: "en-l3-beat", word: "BEAT", language: "english", level: 3, category: "verbs", image: "💓", difficulty: 1, enabled: true },
  { id: "en-l3-heat", word: "HEAT", language: "english", level: 3, category: "verbs", image: "🔥", difficulty: 1, enabled: true },
  { id: "en-l3-meat", word: "MEAT", language: "english", level: 3, category: "food", image: "🥩", difficulty: 1, enabled: true },
  { id: "en-l3-seat", word: "SEAT", language: "english", level: 3, category: "objects", image: "🪑", difficulty: 1, enabled: true },
  { id: "en-l3-jump", word: "JUMP", language: "english", level: 3, category: "verbs", image: "🦘", difficulty: 1, enabled: true },
  { id: "en-l3-kick", word: "KICK", language: "english", level: 3, category: "verbs", image: "🦵", difficulty: 1, enabled: true },
  { id: "en-l3-help", word: "HELP", language: "english", level: 3, category: "verbs", image: "🤝", difficulty: 1, enabled: true },
  { id: "en-l3-rock", word: "ROCK", language: "english", level: 3, category: "objects", image: "🪨", difficulty: 1, enabled: true },
  { id: "en-l3-lock", word: "LOCK", language: "english", level: 3, category: "verbs", image: "🔒", difficulty: 1, enabled: true },
  { id: "en-l3-sock", word: "SOCK", language: "english", level: 3, category: "clothing", image: "🧦", difficulty: 1, enabled: true },
  { id: "en-l3-dock", word: "DOCK", language: "english", level: 3, category: "places", image: "⚓", difficulty: 1, enabled: true },
  { id: "en-l3-math", word: "MATH", language: "english", level: 3, category: "subjects", image: "🔢", difficulty: 1, enabled: true },
  { id: "en-l3-path", word: "PATH", language: "english", level: 3, category: "places", image: "🛤️", difficulty: 1, enabled: true },
  { id: "en-l3-bath", word: "BATH", language: "english", level: 3, category: "rooms", image: "🛁", difficulty: 1, enabled: true },
  { id: "en-l3-face", word: "FACE", language: "english", level: 3, category: "body", image: "😊", difficulty: 1, enabled: true },
  { id: "en-l3-race", word: "RACE", language: "english", level: 3, category: "verbs", image: "🏁", difficulty: 1, enabled: true },
  { id: "en-l3-lace", word: "LACE", language: "english", level: 3, category: "objects", image: "🎀", difficulty: 1, enabled: true },
  { id: "en-l3-pace", word: "PACE", language: "english", level: 3, category: "verbs", image: "🚶", difficulty: 1, enabled: true },
  { id: "en-l3-hose", word: "HOSE", language: "english", level: 3, category: "objects", image: "💧", difficulty: 1, enabled: true },
  { id: "en-l3-nose", word: "NOSE", language: "english", level: 3, category: "body", image: "👃", difficulty: 1, enabled: true },
  { id: "en-l3-rose", word: "ROSE", language: "english", level: 3, category: "flowers", image: "🌹", difficulty: 1, enabled: true },
  { id: "en-l3-date", word: "DATE", language: "english", level: 3, category: "time", image: "📅", difficulty: 1, enabled: true },
  { id: "en-l3-gate", word: "GATE", language: "english", level: 3, category: "objects", image: "🚪", difficulty: 1, enabled: true },
  { id: "en-l3-late", word: "LATE", language: "english", level: 3, category: "adjectives", image: "⏰", difficulty: 1, enabled: true },

  // LEVEL 4 — 67 unique 5-letter words ONLY
  { id: "en-l4-river", word: "RIVER", language: "english", level: 4, category: "nature", image: "🏞️", difficulty: 1, enabled: true },
  { id: "en-l4-house", word: "HOUSE", language: "english", level: 4, category: "places", image: "🏡", difficulty: 1, enabled: true },
  { id: "en-l4-mouse", word: "MOUSE", language: "english", level: 4, category: "animals", image: "🐭", difficulty: 1, enabled: true },
  { id: "en-l4-table", word: "TABLE", language: "english", level: 4, category: "furniture", image: "🪑", difficulty: 1, enabled: true },
  { id: "en-l4-apple", word: "APPLE", language: "english", level: 4, category: "food", image: "🍎", difficulty: 1, enabled: true },
  { id: "en-l4-water", word: "WATER", language: "english", level: 4, category: "nature", image: "💧", difficulty: 1, enabled: true },
  { id: "en-l4-plant", word: "PLANT", language: "english", level: 4, category: "nature", image: "🌱", difficulty: 1, enabled: true },
  { id: "en-l4-train", word: "TRAIN", language: "english", level: 4, category: "transport", image: "🚆", difficulty: 1, enabled: true },
  { id: "en-l4-smile", word: "SMILE", language: "english", level: 4, category: "verbs", image: "😊", difficulty: 1, enabled: true },
  { id: "en-l4-happy", word: "HAPPY", language: "english", level: 4, category: "adjectives", image: "😊", difficulty: 1, enabled: true },
  { id: "en-l4-light", word: "LIGHT", language: "english", level: 4, category: "objects", image: "💡", difficulty: 1, enabled: true },
  { id: "en-l4-night", word: "NIGHT", language: "english", level: 4, category: "time", image: "🌙", difficulty: 1, enabled: true },
  { id: "en-l4-right", word: "RIGHT", language: "english", level: 4, category: "directions", image: "➡️", difficulty: 1, enabled: true },
  { id: "en-l4-fight", word: "FIGHT", language: "english", level: 4, category: "verbs", image: "🥊", difficulty: 1, enabled: true },
  { id: "en-l4-sight", word: "SIGHT", language: "english", level: 4, category: "verbs", image: "👁️", difficulty: 1, enabled: true },
  { id: "en-l4-might", word: "MIGHT", language: "english", level: 4, category: "verbs", image: "💪", difficulty: 1, enabled: true },
  { id: "en-l4-brain", word: "BRAIN", language: "english", level: 4, category: "body", image: "🧠", difficulty: 1, enabled: true },
  { id: "en-l4-ocean", word: "OCEAN", language: "english", level: 4, category: "nature", image: "🌊", difficulty: 1, enabled: true },
  { id: "en-l4-music", word: "MUSIC", language: "english", level: 4, category: "objects", image: "🎵", difficulty: 1, enabled: true },
  { id: "en-l4-magic", word: "MAGIC", language: "english", level: 4, category: "objects", image: "✨", difficulty: 1, enabled: true },
  { id: "en-l4-giant", word: "GIANT", language: "english", level: 4, category: "people", image: "🗿", difficulty: 1, enabled: true },
  { id: "en-l4-angel", word: "ANGEL", language: "english", level: 4, category: "people", image: "😇", difficulty: 1, enabled: true },
  { id: "en-l4-dream", word: "DREAM", language: "english", level: 4, category: "nouns", image: "💭", difficulty: 1, enabled: true },
  { id: "en-l4-clean", word: "CLEAN", language: "english", level: 4, category: "adjectives", image: "🧹", difficulty: 1, enabled: true },
  { id: "en-l4-sleep", word: "SLEEP", language: "english", level: 4, category: "verbs", image: "😴", difficulty: 1, enabled: true },
  { id: "en-l4-sheep", word: "SHEEP", language: "english", level: 4, category: "animals", image: "🐑", difficulty: 1, enabled: true },
  { id: "en-l4-sweet", word: "SWEET", language: "english", level: 4, category: "adjectives", image: "🍭", difficulty: 1, enabled: true },
  { id: "en-l4-wheel", word: "WHEEL", language: "english", level: 4, category: "objects", image: "🛞", difficulty: 1, enabled: true },
  { id: "en-l4-steel", word: "STEEL", language: "english", level: 4, category: "objects", image: "🔩", difficulty: 1, enabled: true },
  { id: "en-l4-three", word: "THREE", language: "english", level: 4, category: "numbers", image: "3️⃣", difficulty: 1, enabled: true },
  { id: "en-l4-green", word: "GREEN", language: "english", level: 4, category: "colors", image: "🟢", difficulty: 1, enabled: true },
  { id: "en-l4-queen", word: "QUEEN", language: "english", level: 4, category: "people", image: "👑", difficulty: 1, enabled: true },
  { id: "en-l4-bread", word: "BREAD", language: "english", level: 4, category: "food", image: "🥖", difficulty: 1, enabled: true },
  { id: "en-l4-beach", word: "BEACH", language: "english", level: 4, category: "places", image: "🏖️", difficulty: 1, enabled: true },
  { id: "en-l4-peach", word: "PEACH", language: "english", level: 4, category: "food", image: "🍑", difficulty: 1, enabled: true },
  { id: "en-l4-reach", word: "REACH", language: "english", level: 4, category: "verbs", image: "🫱", difficulty: 1, enabled: true },
  { id: "en-l4-teach", word: "TEACH", language: "english", level: 4, category: "verbs", image: "👨‍🏫", difficulty: 1, enabled: true },
  { id: "en-l4-chair", word: "CHAIR", language: "english", level: 4, category: "furniture", image: "🪑", difficulty: 1, enabled: true },
  { id: "en-l4-phone", word: "PHONE", language: "english", level: 4, category: "objects", image: "📱", difficulty: 1, enabled: true },
  { id: "en-l4-pizza", word: "PIZZA", language: "english", level: 4, category: "food", image: "🍕", difficulty: 1, enabled: true },
  { id: "en-l4-fruit", word: "FRUIT", language: "english", level: 4, category: "food", image: "🍎", difficulty: 1, enabled: true },
  { id: "en-l4-story", word: "STORY", language: "english", level: 4, category: "books", image: "📚", difficulty: 1, enabled: true },
  { id: "en-l4-glory", word: "GLORY", language: "english", level: 4, category: "nouns", image: "🏆", difficulty: 1, enabled: true },
  { id: "en-l4-worry", word: "WORRY", language: "english", level: 4, category: "verbs", image: "😟", difficulty: 1, enabled: true },
  { id: "en-l4-hurry", word: "HURRY", language: "english", level: 4, category: "verbs", image: "⏱️", difficulty: 1, enabled: true },
  { id: "en-l4-berry", word: "BERRY", language: "english", level: 4, category: "food", image: "🫐", difficulty: 1, enabled: true },
  { id: "en-l4-carry", word: "CARRY", language: "english", level: 4, category: "verbs", image: "🚚", difficulty: 1, enabled: true },
  { id: "en-l4-merry", word: "MERRY", language: "english", level: 4, category: "adjectives", image: "🎄", difficulty: 1, enabled: true },
  { id: "en-l4-sorry", word: "SORRY", language: "english", level: 4, category: "adjectives", image: "😔", difficulty: 1, enabled: true },
  { id: "en-l4-fairy", word: "FAIRY", language: "english", level: 4, category: "people", image: "🧚", difficulty: 1, enabled: true },
  { id: "en-l4-hairy", word: "HAIRY", language: "english", level: 4, category: "adjectives", image: "💈", difficulty: 1, enabled: true },
  { id: "en-l4-dairy", word: "DAIRY", language: "english", level: 4, category: "food", image: "🥛", difficulty: 1, enabled: true },
  { id: "en-l4-scary", word: "SCARY", language: "english", level: 4, category: "adjectives", image: "👻", difficulty: 1, enabled: true },
  { id: "en-l4-early", word: "EARLY", language: "english", level: 4, category: "adjectives", image: "🌅", difficulty: 1, enabled: true },
  { id: "en-l4-party", word: "PARTY", language: "english", level: 4, category: "events", image: "🎉", difficulty: 1, enabled: true },
  { id: "en-l4-dirty", word: "DIRTY", language: "english", level: 4, category: "adjectives", image: "🤪", difficulty: 1, enabled: true },
  { id: "en-l4-empty", word: "EMPTY", language: "english", level: 4, category: "adjectives", image: "🚫", difficulty: 1, enabled: true },
  { id: "en-l4-angry", word: "ANGRY", language: "english", level: 4, category: "adjectives", image: "😠", difficulty: 1, enabled: true },
  { id: "en-l4-ready", word: "READY", language: "english", level: 4, category: "adjectives", image: "✅", difficulty: 1, enabled: true },
  { id: "en-l4-watch", word: "WATCH", language: "english", level: 4, category: "verbs", image: "⌚", difficulty: 1, enabled: true },
  { id: "en-l4-match", word: "MATCH", language: "english", level: 4, category: "objects", image: "🔥", difficulty: 1, enabled: true },
  { id: "en-l4-catch", word: "CATCH", language: "english", level: 4, category: "verbs", image: "🤾", difficulty: 1, enabled: true },
  { id: "en-l4-batch", word: "BATCH", language: "english", level: 4, category: "nouns", image: "📦", difficulty: 1, enabled: true },
  { id: "en-l4-patch", word: "PATCH", language: "english", level: 4, category: "objects", image: "🩹", difficulty: 1, enabled: true },
  { id: "en-l4-latch", word: "LATCH", language: "english", level: 4, category: "objects", image: "🔐", difficulty: 1, enabled: true },
  { id: "en-l4-hatch", word: "HATCH", language: "english", level: 4, category: "objects", image: "🐣", difficulty: 1, enabled: true },
  { id: "en-l4-fetch", word: "FETCH", language: "english", level: 4, category: "verbs", image: "🐕", difficulty: 1, enabled: true },

  // LEVEL 5 — 77 unique 6+ letter words ONLY
  { id: "en-l5-butterfly", word: "BUTTERFLY", language: "english", level: 5, category: "animals", image: "🦋", difficulty: 1, enabled: true },
  { id: "en-l5-adventure", word: "ADVENTURE", language: "english", level: 5, category: "nouns", image: "🗺️", difficulty: 1, enabled: true },
  { id: "en-l5-computer", word: "COMPUTER", language: "english", level: 5, category: "objects", image: "💻", difficulty: 1, enabled: true },
  { id: "en-l5-birthday", word: "BIRTHDAY", language: "english", level: 5, category: "events", image: "🎂", difficulty: 1, enabled: true },
  { id: "en-l5-elephant", word: "ELEPHANT", language: "english", level: 5, category: "animals", image: "🐘", difficulty: 1, enabled: true },
  { id: "en-l5-chocolate", word: "CHOCOLATE", language: "english", level: 5, category: "food", image: "🍫", difficulty: 1, enabled: true },
  { id: "en-l5-rainbow", word: "RAINBOW", language: "english", level: 5, category: "nature", image: "🌈", difficulty: 1, enabled: true },
  { id: "en-l5-sunshine", word: "SUNSHINE", language: "english", level: 5, category: "nature", image: "☀️", difficulty: 1, enabled: true },
  { id: "en-l5-laughter", word: "LAUGHTER", language: "english", level: 5, category: "nouns", image: "😂", difficulty: 1, enabled: true },
  { id: "en-l5-wonderful", word: "WONDERFUL", language: "english", level: 5, category: "adjectives", image: "⭐", difficulty: 1, enabled: true },
  { id: "en-l5-kindness", word: "KINDNESS", language: "english", level: 5, category: "nouns", image: "💖", difficulty: 1, enabled: true },
  { id: "en-l5-happiness", word: "HAPPINESS", language: "english", level: 5, category: "nouns", image: "😊", difficulty: 1, enabled: true },
  { id: "en-l5-treasure", word: "TREASURE", language: "english", level: 5, category: "nouns", image: "💎", difficulty: 1, enabled: true },
  { id: "en-l5-library", word: "LIBRARY", language: "english", level: 5, category: "places", image: "📚", difficulty: 1, enabled: true },
  { id: "en-l5-mystery", word: "MYSTERY", language: "english", level: 5, category: "books", image: "🔍", difficulty: 1, enabled: true },
  { id: "en-l5-victory", word: "VICTORY", language: "english", level: 5, category: "nouns", image: "🏆", difficulty: 1, enabled: true },
  { id: "en-l5-journey", word: "JOURNEY", language: "english", level: 5, category: "nouns", image: "🛤️", difficulty: 1, enabled: true },
  { id: "en-l5-kitchen", word: "KITCHEN", language: "english", level: 5, category: "rooms", image: "🍳", difficulty: 1, enabled: true },
  { id: "en-l5-chicken", word: "CHICKEN", language: "english", level: 5, category: "animals", image: "🐔", difficulty: 1, enabled: true },
  { id: "en-l5-penguin", word: "PENGUIN", language: "english", level: 5, category: "animals", image: "🐧", difficulty: 1, enabled: true },
  { id: "en-l5-dolphin", word: "DOLPHIN", language: "english", level: 5, category: "animals", image: "🐬", difficulty: 1, enabled: true },
  { id: "en-l5-student", word: "STUDENT", language: "english", level: 5, category: "people", image: "👨‍🎓", difficulty: 1, enabled: true },
  { id: "en-l5-teacher", word: "TEACHER", language: "english", level: 5, category: "people", image: "👨‍🏫", difficulty: 1, enabled: true },
  { id: "en-l5-captain", word: "CAPTAIN", language: "english", level: 5, category: "people", image: "⛵", difficulty: 1, enabled: true },
  { id: "en-l5-warrior", word: "WARRIOR", language: "english", level: 5, category: "people", image: "⚔️", difficulty: 1, enabled: true },
  { id: "en-l5-monster", word: "MONSTER", language: "english", level: 5, category: "creatures", image: "👹", difficulty: 1, enabled: true },
  { id: "en-l5-whisper", word: "WHISPER", language: "english", level: 5, category: "verbs", image: "🤫", difficulty: 1, enabled: true },
  { id: "en-l5-thunder", word: "THUNDER", language: "english", level: 5, category: "nature", image: "⛈️", difficulty: 1, enabled: true },
  { id: "en-l5-chamber", word: "CHAMBER", language: "english", level: 5, category: "places", image: "🏰", difficulty: 1, enabled: true },
  { id: "en-l5-chapter", word: "CHAPTER", language: "english", level: 5, category: "books", image: "📖", difficulty: 1, enabled: true },
  { id: "en-l5-painter", word: "PAINTER", language: "english", level: 5, category: "people", image: "🎨", difficulty: 1, enabled: true },
  { id: "en-l5-pointer", word: "POINTER", language: "english", level: 5, category: "objects", image: "👆", difficulty: 1, enabled: true },
  { id: "en-l5-shelter", word: "SHELTER", language: "english", level: 5, category: "places", image: "🏛️", difficulty: 1, enabled: true },
  { id: "en-l5-weather", word: "WEATHER", language: "english", level: 5, category: "nature", image: "🌤️", difficulty: 1, enabled: true },
  { id: "en-l5-feather", word: "FEATHER", language: "english", level: 5, category: "nature", image: "🪶", difficulty: 1, enabled: true },
  { id: "en-l5-leather", word: "LEATHER", language: "english", level: 5, category: "objects", image: "👜", difficulty: 1, enabled: true },
  { id: "en-l5-battery", word: "BATTERY", language: "english", level: 5, category: "objects", image: "🔋", difficulty: 1, enabled: true },
  { id: "en-l5-pottery", word: "POTTERY", language: "english", level: 5, category: "objects", image: "🏺", difficulty: 1, enabled: true },
  { id: "en-l5-gallery", word: "GALLERY", language: "english", level: 5, category: "places", image: "🖼️", difficulty: 1, enabled: true },
  { id: "en-l5-factory", word: "FACTORY", language: "english", level: 5, category: "places", image: "🏭", difficulty: 1, enabled: true },
  { id: "en-l5-history", word: "HISTORY", language: "english", level: 5, category: "subjects", image: "📜", difficulty: 1, enabled: true },
  { id: "en-l5-biology", word: "BIOLOGY", language: "english", level: 5, category: "subjects", image: "🔬", difficulty: 1, enabled: true },
  { id: "en-l5-company", word: "COMPANY", language: "english", level: 5, category: "nouns", image: "👥", difficulty: 1, enabled: true },
  { id: "en-l5-harmony", word: "HARMONY", language: "english", level: 5, category: "music", image: "🎼", difficulty: 1, enabled: true },
  { id: "en-l5-honesty", word: "HONESTY", language: "english", level: 5, category: "nouns", image: "✨", difficulty: 1, enabled: true },
  { id: "en-l5-mastery", word: "MASTERY", language: "english", level: 5, category: "nouns", image: "🏅", difficulty: 1, enabled: true },
  { id: "en-l5-nursery", word: "NURSERY", language: "english", level: 5, category: "places", image: "👶", difficulty: 1, enabled: true },
  { id: "en-l5-archery", word: "ARCHERY", language: "english", level: 5, category: "sports", image: "🏹", difficulty: 1, enabled: true },
  { id: "en-l5-archway", word: "ARCHWAY", language: "english", level: 5, category: "places", image: "🏛️", difficulty: 1, enabled: true },
  { id: "en-l5-halfway", word: "HALFWAY", language: "english", level: 5, category: "places", image: "🔀", difficulty: 1, enabled: true },
  { id: "en-l5-holiday", word: "HOLIDAY", language: "english", level: 5, category: "events", image: "🎉", difficulty: 1, enabled: true },
  { id: "en-l5-quality", word: "QUALITY", language: "english", level: 5, category: "nouns", image: "⭐", difficulty: 1, enabled: true },
  { id: "en-l5-penalty", word: "PENALTY", language: "english", level: 5, category: "games", image: "🚫", difficulty: 1, enabled: true },
  { id: "en-l5-loyalty", word: "LOYALTY", language: "english", level: 5, category: "nouns", image: "🤝", difficulty: 1, enabled: true },
  { id: "en-l5-royalty", word: "ROYALTY", language: "english", level: 5, category: "people", image: "👑", difficulty: 1, enabled: true },
  { id: "en-l5-century", word: "CENTURY", language: "english", level: 5, category: "time", image: "⏰", difficulty: 1, enabled: true },
  { id: "en-l5-energy", word: "ENERGY", language: "english", level: 5, category: "nouns", image: "⚡", difficulty: 1, enabled: true },
  { id: "en-l5-summary", word: "SUMMARY", language: "english", level: 5, category: "nouns", image: "📋", difficulty: 1, enabled: true },
  { id: "en-l5-primary", word: "PRIMARY", language: "english", level: 5, category: "adjectives", image: "🔴", difficulty: 1, enabled: true },
  { id: "en-l5-mercury", word: "MERCURY", language: "english", level: 5, category: "planets", image: "☿️", difficulty: 1, enabled: true },
  { id: "en-l5-jewelry", word: "JEWELRY", language: "english", level: 5, category: "objects", image: "💎", difficulty: 1, enabled: true },
  { id: "en-l5-pattern", word: "PATTERN", language: "english", level: 5, category: "nouns", image: "🎨", difficulty: 1, enabled: true },
  { id: "en-l5-lantern", word: "LANTERN", language: "english", level: 5, category: "objects", image: "🏮", difficulty: 1, enabled: true },
  { id: "en-l5-pancake", word: "PANCAKE", language: "english", level: 5, category: "food", image: "🥞", difficulty: 1, enabled: true },
  { id: "en-l5-picture", word: "PICTURE", language: "english", level: 5, category: "objects", image: "🖼️", difficulty: 1, enabled: true },
  { id: "en-l5-monster2", word: "MONSTER", language: "english", level: 5, category: "creatures", image: "👹", difficulty: 1, enabled: false },
  { id: "en-l5-island", word: "ISLAND", language: "english", level: 5, category: "places", image: "🏝️", difficulty: 1, enabled: true },
  { id: "en-l5-forest", word: "FOREST", language: "english", level: 5, category: "nature", image: "🌲", difficulty: 1, enabled: true },
  { id: "en-l5-mountain", word: "MOUNTAIN", language: "english", level: 5, category: "nature", image: "⛰️", difficulty: 1, enabled: true },
  { id: "en-l5-castle", word: "CASTLE", language: "english", level: 5, category: "places", image: "🏰", difficulty: 1, enabled: true },
  { id: "en-l5-market", word: "MARKET", language: "english", level: 5, category: "places", image: "🛍️", difficulty: 1, enabled: true },
  { id: "en-l5-basket", word: "BASKET", language: "english", level: 5, category: "objects", image: "🧺", difficulty: 1, enabled: true },
  { id: "en-l5-carpet", word: "CARPET", language: "english", level: 5, category: "furniture", image: "🧶", difficulty: 1, enabled: true },
  { id: "en-l5-helmet", word: "HELMET", language: "english", level: 5, category: "clothing", image: "⛑️", difficulty: 1, enabled: true },
  { id: "en-l5-jacket", word: "JACKET", language: "english", level: 5, category: "clothing", image: "🧥", difficulty: 1, enabled: true },
  { id: "en-l5-pocket", word: "POCKET", language: "english", level: 5, category: "clothing", image: "👖", difficulty: 1, enabled: true },
  { id: "en-l5-ticket", word: "TICKET", language: "english", level: 5, category: "objects", image: "🎫", difficulty: 1, enabled: true },
  { id: "en-l5-banner", word: "BANNER", language: "english", level: 5, category: "objects", image: "🚩", difficulty: 1, enabled: true },
];

// Utility Functions
export function getWordsForLevel(language: Language, level: number): Word[] {
  const datasets: Record<Language, Word[]> = {
    english: ENGLISH_WORDS,
    yoruba: [],
    french: [],
    igbo: [],
    hausa: [],
  };
  
  return datasets[language].filter(w => w.level === level && w.enabled);
}

export function getAllWords(language: Language): Word[] {
  const datasets: Record<Language, Word[]> = {
    english: ENGLISH_WORDS,
    yoruba: [],
    french: [],
    igbo: [],
    hausa: [],
  };
  
  return datasets[language].filter(w => w.enabled);
}

export function getRandomWord(language: Language, level: number): Word | undefined {
  const words = getWordsForLevel(language, level);
  if (words.length === 0) return undefined;
  return words[Math.floor(Math.random() * words.length)];
}

export function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

// Export for use in game
export const wordDatasets: Record<Language, Word[]> = {
  english: ENGLISH_WORDS,
  yoruba: [],
  french: [],
  igbo: [],
  hausa: [],
};

export default wordDatasets;
