import type { StoryPage } from "@/types/stories";

export const nigeriasIndependencePages: StoryPage[] = [
  {
    pageNumber: 1,
    type: "narrative",
    text: "Nigeria's Independence • The Story of October 1st!\n\nFor Little Explorers • Ages 0–11\n\nGrab your imaginary backpack!\nPut on your explorer hat!\nAnd let's travel back in time!\n\nOctober 1, 1960 — A very special date in Nigeria's story.\n\nLearn • Play • Think • Dream Big!",
    audioText: "Nigeria's Independence. The Story of October 1st. For Little Explorers ages 0 to 11. Grab your imaginary backpack. Put on your explorer hat. And let's travel back in time. October 1, 1960 is a very special date in Nigeria's story. Learn, Play, Think, and Dream Big!",
    imageUrl: "/stories/nigerias-independence/page-01.png",
  },
  {
    pageNumber: 2,
    type: "narrative",
    text: "Hey, Little Explorer!\n\nHave you ever wondered… Why do Nigerians celebrate October 1st?\n\nOur adventure begins a long, long time ago. Nigeria was not yet an independent country.\n\nExplorer Tip: Ask a grown-up to pause here and talk about what you just learned!",
    audioText: "Hey, Little Explorer! Have you ever wondered why Nigerians celebrate October 1st? Our adventure begins a long, long time ago. Nigeria was not yet an independent country. Explorer Tip: Ask a grown-up to pause here and talk about what you just learned!",
    imageUrl: "/stories/nigerias-independence/page-02.jfif",
  },
  {
    pageNumber: 3,
    type: "narrative",
    text: "Chapter 1: Nigeria Long Ago\n\nDifferent groups of people lived in different parts of the land. They had their own:\n• Languages\n• Foods\n• Clothes\n• Songs\n• Traditions\n• Ways of life\n\nNigeria was already full of wonderful people and cultures!\n\nBut there was something important happening…\nBritain was ruling Nigeria.\n\nMany Nigerians wanted to choose their own leaders, speak up about their ideas, make important decisions, and lead their own country.\n\nExplorer Tip: Ask a grown-up to pause here and talk about what you just learned!",
    audioText: "Chapter 1: Nigeria Long Ago. Different groups of people lived in different parts of the land. They had their own languages, foods, clothes, songs, traditions, and ways of life. Nigeria was already full of wonderful people and cultures! But there was something important happening. Britain was ruling Nigeria. Many Nigerians wanted to choose their own leaders, speak up about their ideas, make important decisions, and lead their own country. Explorer Tip: Ask a grown-up to pause here and talk about what you just learned!",
    imageUrl: "/stories/nigerias-independence/page-03.jfif",
  },
  {
    pageNumber: 4,
    type: "milestone",
    text: "1960 ARRIVED!\n\nSomething BIG was about to happen!\n\nOctober 1, 1960\n\nNigeria became independent from British rule. People celebrated because it was the beginning of a new chapter for the country.",
    audioText: "1960 arrived! Something big was about to happen! October 1, 1960. Nigeria became independent from British rule. People celebrated because it was the beginning of a new chapter for the country.",
    imageUrl: "/stories/nigerias-independence/page-04.jfif",
  },
  {
    pageNumber: 5,
    type: "explanation",
    text: "What Does Independence Mean?\n\nLet's make it super simple!\n\nIndependence means a country can lead itself.\n\nFor Nigeria, becoming independent meant Nigerians could begin to choose their own leaders and make important decisions for their country.",
    audioText: "What Does Independence Mean? Let's make it super simple! Independence means a country can lead itself. For Nigeria, becoming independent meant Nigerians could begin to choose their own leaders and make important decisions for their country.",
    imageUrl: "/stories/nigerias-independence/page-05.jfif",
  },
  {
    pageNumber: 6,
    type: "reflection",
    text: "STOP & THINK!\n\nImagine you and your friends are playing a game. Would you like to have a say in:\n• Which game you play?\n• What the rules should be?\n• Who helps organise the game?\n\nA country can also want to have a say in how it is led. That's one way to begin understanding independence!",
    audioText: "Stop and think. Imagine you and your friends are playing a game. Would you like to have a say in which game you play, what the rules should be, and who helps organise the game? A country can also want to have a say in how it is led. That's one way to begin understanding independence!",
    imageUrl: "/stories/nigerias-independence/page-06.jfif",
  },
  {
    pageNumber: 7,
    type: "narrative",
    text: "It Took Time!\n\nNigeria did not become independent overnight. It was a long journey.\n\nMany Nigerians wanted independence. They worked, spoke up, and helped bring about change.\n\nThen came the very important year: 1960\n\nAnd on October 1, 1960, Nigeria became independent!",
    audioText: "It Took Time! Nigeria did not become independent overnight. It was a long journey. Many Nigerians wanted independence. They worked, spoke up, and helped bring about change. Then came the very important year, 1960. And on October 1, 1960, Nigeria became independent!",
    imageUrl: "/stories/nigerias-independence/page-07.jfif",
  },
  {
    pageNumber: 8,
    type: "fact",
    text: "DID YOU KNOW?\n\n1. The Magic Year: 1960 was a very special year in Nigeria's history.\n\n2. The Special Date: October 1, 1960 is the date Nigeria became independent.\n\n3. Before Independence: Britain ruled Nigeria before independence.\n\n4. Big Decisions: After independence, Nigeria could have her own leaders and make important decisions.",
    audioText: "Did you know? The Magic Year is 1960, which was a very special year in Nigeria's history. The Special Date is October 1, 1960, when Nigeria became independent. Before Independence, Britain ruled Nigeria. Big Decisions: After independence, Nigeria could have her own leaders and make important decisions.",
    imageUrl: "/stories/nigerias-independence/page-08.jfif",
  },
  {
    pageNumber: 9,
    type: "character",
    text: "Meet Nigeria's First Prime Minister!\n\nCan you remember his name?\n\nSir Abubakar Tafawa Balewa\n\nHe became Nigeria's first Prime Minister when Nigeria became independent.\n\nMemory Trick:\nA-bu-ba-kar • Ta-fa-wa • Ba-le-wa!\n\nNow try saying it without looking!",
    audioText: "Meet Nigeria's First Prime Minister. Can you remember his name? Sir Abubakar Tafawa Balewa. He became Nigeria's first Prime Minister when Nigeria became independent. Memory Trick: A-bu-ba-kar, Ta-fa-wa, Ba-le-wa. Now try saying it without looking!",
    imageUrl: "/stories/nigerias-independence/page-09.jfif",
  },
  {
    pageNumber: 10,
    type: "narrative",
    text: "Independence Was a Happy Time!\n\nPeople were happy and celebrated this very important moment. It was the beginning of a new chapter for Nigeria.\n\nOld chapter: The journey to independence\n\nNew chapter: Nigeria's journey as an independent nation",
    audioText: "Independence was a happy time! People were happy and celebrated this very important moment. It was the beginning of a new chapter for Nigeria. Old chapter: The journey to independence. New chapter: Nigeria's journey as an independent nation.",
    imageUrl: "/stories/nigerias-independence/page-10.jfif",
  },
  {
    pageNumber: 11,
    type: "narrative",
    text: "Nigeria Is Full of Wonderful People!\n\nNigeria is home to many people with different:\n• Languages\n• Foods\n• Clothes\n• Songs\n• Traditions\n\nAnd guess what?\n\nThey are all part of Nigeria!\n\nDifferent can be beautiful.",
    audioText: "Nigeria Is Full of Wonderful People! Nigeria is home to many people with different languages, foods, clothes, songs, and traditions. And guess what? They are all part of Nigeria! Different can be beautiful.",
    imageUrl: "/stories/nigerias-independence/page-11.jfif",
  },
  {
    pageNumber: 12,
    type: "symbol",
    text: "The Nigerian Flag\n\nLook closely at the Nigerian flag!\n\nGREEN • WHITE • GREEN\n\nGreen and white are Nigeria's national colours.\n\nFLAG CHALLENGE!\n\nCan you draw the Nigerian flag? Remember: GREEN | WHITE | GREEN",
    audioText: "The Nigerian Flag. Look closely at the Nigerian flag! Green, White, Green. Green and white are Nigeria's national colours. Flag Challenge: Can you draw the Nigerian flag? Remember: Green, White, Green.",
    imageUrl: "/stories/nigerias-independence/page-12.jfif",
  },
  {
    pageNumber: 13,
    type: "narrative",
    text: "Nigeria Joins the World\n\nA few days after becoming independent, Nigeria joined the United Nations.\n\nThe United Nations is a big group that brings countries from around the world together.",
    audioText: "Nigeria Joins the World. A few days after becoming independent, Nigeria joined the United Nations. The United Nations is a big group that brings countries from around the world together.",
    imageUrl: "/stories/nigerias-independence/page-13.jfif",
  },
  {
    pageNumber: 14,
    type: "celebration",
    text: "Independence Day Every Year!\n\nEvery year on October 1, Nigerians remember independence. It is a chance to remember Nigeria's history and the people and events that helped shape the country.\n\nHappy Independence Day, Nigeria!",
    audioText: "Independence Day Every Year! Every year on October 1, Nigerians remember independence. It is a chance to remember Nigeria's history and the people and events that helped shape the country. Happy Independence Day, Nigeria!",
    imageUrl: "/stories/nigerias-independence/page-14.jfif",
  },
  {
    pageNumber: 15,
    type: "reflection",
    text: "What Can WE Learn?\n\nThe story of independence isn't just about something that happened long ago. It can also teach us things we can practise today!",
    audioText: "What Can We Learn? The story of independence isn't just about something that happened long ago. It can also teach us things we can practise today!",
    imageUrl: "/stories/nigerias-independence/page-15.jfif",
  },
  {
    pageNumber: 16,
    type: "learning",
    text: "❤ LOVE OUR COUNTRY\n\nNigeria is our home. We can show love for our country by taking care of our homes, schools, streets, and the people around us.\n\nTiny Action: Pick up one piece of litter today. Small hands can make a big difference!",
    audioText: "Love Our Country. Nigeria is our home. We can show love for our country by taking care of our homes, schools, streets, and the people around us. Tiny Action: Pick up one piece of litter today. Small hands can make a big difference!",
    imageUrl: "/stories/nigerias-independence/page-16.jfif",
  },
  {
    pageNumber: 17,
    type: "learning",
    text: "WORK TOGETHER\n\nWhen we help each other, we can do more.\n\n\"Little hands can do BIG things!\"\n\nYou can help a friend, share your toys, help someone learn, or help at home.",
    audioText: "Work Together. When we help each other, we can do more. Little hands can do big things! You can help a friend, share your toys, help someone learn, or help at home.",
    imageUrl: "/stories/nigerias-independence/page-17.jfif",
  },
  {
    pageNumber: 18,
    type: "learning",
    text: "USE YOUR VOICE\n\nYour words matter! You can share your ideas, speak kindly, ask questions, and tell a trusted grown-up when something isn't right.\n\nYour voice can be used to help, not hurt.",
    audioText: "Use Your Voice. Your words matter! You can share your ideas, speak kindly, ask questions, and tell a trusted grown-up when something isn't right. Your voice can be used to help, not hurt.",
    imageUrl: "/stories/nigerias-independence/page-18.jfif",
  },
  {
    pageNumber: 19,
    type: "learning",
    text: "HELP OTHERS\n\nHelping someone doesn't have to be a huge thing.\n\nSmile at someone • Lend a helping hand • Share • Care • Be kind",
    audioText: "Help Others. Helping someone doesn't have to be a huge thing. Smile at someone. Lend a helping hand. Share. Care. Be kind.",
    imageUrl: "/stories/nigerias-independence/page-19.jfif",
  },
  {
    pageNumber: 20,
    type: "learning",
    text: "BE PROUD\n\nYou can be proud to be Nigerian! Learn about Nigeria's people, music, food, cultures, places, and history.\n\nThe more we learn, the more we understand our country.",
    audioText: "Be Proud. You can be proud to be Nigerian! Learn about Nigeria's people, music, food, cultures, places, and history. The more we learn, the more we understand our country.",
    imageUrl: "/stories/nigerias-independence/page-20.jfif",
  },
  {
    pageNumber: 21,
    type: "learning",
    text: "LEARN FROM THE PAST\n\nHistory tells us stories about things that happened before we were born.\n\nWhen we learn about the past, we can better understand our country today.\n\nHistory = Stories from the past that help us understand today!",
    audioText: "Learn From The Past. History tells us stories about things that happened before we were born. When we learn about the past, we can better understand our country today. History equals Stories from the past that help us understand today!",
    imageUrl: "/stories/nigerias-independence/page-21.jfif",
  },
  {
    pageNumber: 22,
    type: "inspiration",
    text: "DREAM BIG!\n\nYou are a child today… but one day, you will grow up and have the chance to use your talents to help Nigeria.\n\nDoctor • Teacher • Scientist • Programmer\nArtist • Farmer • Leader • Inventor\n\nOr something nobody has even imagined yet!\n\nYOUR FUTURE CAN BE BIG!\n\nLearn. Grow. Help others. Dream big.",
    audioText: "Dream Big! You are a child today, but one day you will grow up and have the chance to use your talents to help Nigeria. Doctor, Teacher, Scientist, Programmer, Artist, Farmer, Leader, Inventor. Or something nobody has even imagined yet! Your Future Can Be Big! Learn. Grow. Help others. Dream big.",
    imageUrl: "/stories/nigerias-independence/page-22.jfif",
  },
  {
    pageNumber: 23,
    type: "game",
    text: "LET'S PLAY!\n\nGAME 1: GUESS THE DAY\nWhat special day do Nigerians celebrate on October 1st?\nA. Children's Day\nB. Independence Day\nC. Sports Day\nAnswer: B — Independence Day!\n\nGAME 2: REMEMBER THE YEAR\nWhat year did Nigeria become independent?\nA. 1960\nB. 1970\nC. 2000\nAnswer: A — 1960!\n\nGAME 3: FLAG FUN!\nWhat colours are on Nigeria's flag?\nGreen, White, Green!\n\nExplorer Tip: Ask a grown-up to pause here and talk about what you just learned!",
    audioText: "Let's Play! Game 1: Guess The Day. What special day do Nigerians celebrate on October 1st? A, Children's Day. B, Independence Day. C, Sports Day. Answer: B, Independence Day! Game 2: Remember The Year. What year did Nigeria become independent? A, 1960. B, 1970. C, 2000. Answer: A, 1960! Game 3: Flag Fun! What colours are on Nigeria's flag? Green, White, Green! Explorer Tip: Ask a grown-up to pause here and talk about what you just learned!",
    imageUrl: "/stories/nigerias-independence/page-23.jfif",
  },
  {
    pageNumber: 24,
    type: "game",
    text: "MINI MEMORY GAME\n\nComplete the sentence:\nNigeria became independent on ______________.\n\nHint: October ___, 1960\n\nOCTOBER 1, 1960!",
    audioText: "Mini Memory Game. Complete the sentence: Nigeria became independent on _______________. Hint: October, 1960. October 1, 1960!",
    imageUrl: "/stories/nigerias-independence/page-24.jfif",
  },
  {
    pageNumber: 25,
    type: "activity",
    text: "IMAGINE THIS!\n\nIf you could send Nigeria a birthday card on Independence Day, what would you write?\n\n\"Dear Nigeria…\"\n\nDraw a picture and finish the sentence:\n\"I love Nigeria because…\"",
    audioText: "Imagine This! If you could send Nigeria a birthday card on Independence Day, what would you write? Dear Nigeria. Draw a picture and finish the sentence: I love Nigeria because.",
    imageUrl: "/stories/nigerias-independence/page-25.jfif",
  },
  {
    pageNumber: 26,
    type: "challenge",
    text: "YOUR LITTLE NIGERIAN CHALLENGE\n\nChoose ONE thing you can do this week to help make Nigeria better.\n\n☐ Help someone\n☐ Keep my surroundings clean\n☐ Learn something new about Nigeria\n☐ Be kind to someone\n☐ Help at home\n☐ Share with someone\n\nWhat will YOU choose?",
    audioText: "Your Little Nigerian Challenge. Choose one thing you can do this week to help make Nigeria better. Help someone. Keep my surroundings clean. Learn something new about Nigeria. Be kind to someone. Help at home. Share with someone. What will you choose?",
    imageUrl: "/stories/nigerias-independence/page-26.jfif",
  },
  {
    pageNumber: 27,
    type: "quiz",
    text: "THE BIG QUIZ!\n\n1. What is Nigeria's Independence Day?\n2. What year did Nigeria become independent?\n3. Who ruled Nigeria before independence?\n4. What are the colours of the Nigerian flag?\n5. What was the name of Nigeria's first Prime Minister?\n6. What can YOU do to help your country?",
    audioText: "The Big Quiz! 1. What is Nigeria's Independence Day? 2. What year did Nigeria become independent? 3. Who ruled Nigeria before independence? 4. What are the colours of the Nigerian flag? 5. What was the name of Nigeria's first Prime Minister? 6. What can you do to help your country?",
    imageUrl: "/stories/nigerias-independence/page-27.jfif",
  },
  {
    pageNumber: 28,
    type: "challenge",
    text: "ONE LAST CHALLENGE!\n\nCan you say the special date without looking?\n\n# OCTOBER 1, 1960!\n\nYES! YOU DID IT!",
    audioText: "One Last Challenge! Can you say the special date without looking? October 1, 1960! Yes! You did it!",
    imageUrl: "/stories/nigerias-independence/page-28.jfif",
  },
  {
    pageNumber: 29,
    type: "ending",
    text: "AND THAT'S OUR STORY!\n\nNow you know a little more about Nigeria's independence and why October 1st is such a special day.\n\n❤ Love • Help • Speak kindly\nLearn • Care • Dream BIG!\n\nBecause…\nNIGERIA IS OUR HOME.\n\nAnd even little hands can do BIG things!\n\nHAPPY INDEPENDENCE DAY, NIGERIA!",
    audioText: "And that's our story! Now you know a little more about Nigeria's independence and why October 1st is such a special day. Love. Help. Speak kindly. Learn. Care. Dream big! Because Nigeria is our home. And even little hands can do big things! Happy Independence Day, Nigeria!",
    imageUrl: "/stories/nigerias-independence/page-29.jfif",
  },
];
